services:
  eluvision:
    container_name: eluvision
    build:  ./src
    env_file: .env
    ports:
      - "5173:5173"
      - "4173:4173"


volumes:
  src-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/
