let departments_preposition = {
    "Ain": " de l'",
    "Aisne": " de l'",
    "Allier": " de l'",
    "Alpes-de-Haute-Provence": " des ",
    "Alpes-Maritimes": " des ",
    "Ardèche": " de l'",
    "Ardennes": " des ",
    "Ariège": " de l'",
    "Aube": " de l'",
    "Aude": " de l'",
    "Aveyron": " de l'",
    "Bas-Rhin": " du ",
    "Bouches-du-Rhône": " des ",
    "Calvados": " du ",
    "Cantal": " du ",
    "Charente": " de la ",
    "Charente-Maritime": " de la ",
    "Cher": " du ",
    "Corrèze": " de la ",
    "Corse-du-Sud": " de la ",
    "Côte-d'Or": " de la ",
    "Côtes-d'Armor": " des ",
    "Creuse": " de la ",
    "Deux-Sèvres": " des ",
    "Dordogne": " de la ",
    "Doubs": " du ",
    "Drôme": " de la ",
    "Essonne": " de l'",
    "Eure": " de l'",
    "Eure-et-Loir": " de l'",
    "Finistère": " du ",
    "Français établis hors de France": " des ",
    "Gard": " du ",
    "Gers": " du ",
    "Gironde": " de la ",
    "Guadeloupe": " de la ",
    "Guyane": " de la ",
    "Haut-Rhin": " du ",
    "Haute-Corse": " de la ",
    "Haute-Garonne": " de la ",
    "Haute-Loire": " de la ",
    "Haute-Marne": " de la ",
    "Haute-Saône": " de la ",
    "Haute-Savoie": " de la",
    "Haute-Vienne": " de la",
    "Hautes-Alpes": " des ",
    "Hautes-Pyrénées": " des ",
    "Hauts-de-Seine": " des ",
    "Hérault": " de l'",
    "Ille-et-Vilaine": " de l'",
    "Indre": " de l'",
    "Indre-et-Loire": " de l'",
    "Isère": " de l'",
    "Jura": " du ",
    "Landes": " des ",
    "Loir-et-Cher": " du ",
    "Loire": " de la ",
    "Loire-Atlantique": " de la ",
    "Loiret": " du ",
    "Lot": " du ",
    "Lot-et-Garonne": " du ",
    "Lozère": " de la ",
    "Maine-et-Loire": " de ",
    "Manche": " de la ",
    "Marne": " de la ",
    "Martinique": " de la ",
    "Mayenne": " de la ",
    "Mayotte": " de ",
    "Meurthe-et-Moselle": " de ",
    "Meuse": " de la ",
    "Morbihan": " du ",
    "Moselle": " de la ",
    "Nièvre": " de la ",
    "Nord": " du ",
    "Nouvelle-Calédonie": " de la ",
    "Oise": " de l'",
    "Orne": " de l'",
    "Paris": " de ",
    "Pas-de-Calais": " du ",
    "Polynésie Française": " de la ",
    "Puy-de-Dôme": " du ",
    "Pyrénées-Atlantiques": " des ",
    "Pyrénées-Orientales": " des ",
    "Réunion": " de la ",
    "Rhône": " du ",
    "Saint-Barthélemy et Saint-Martin": " de ",
    "Saint-Pierre-et-Miquelon": " de ",
    "Saône-et-Loire": " de ",
    "Sarthe": " de la ",
    "Savoie": " de la ",
    "Seine-et-Marne": " de ",
    "Seine-Maritime": " de la ",
    "Seine-Saint-Denis": " de la ",
    "Somme": " de la ",
    "Tarn": " du ",
    "Tarn-et-Garonne": " de ",
    "Territoire de Belfort": " du ",
    "Val-d'Oise": " du ",
    "Val-de-Marne": " du ",
    "Var": " du ",
    "Vaucluse": " du ",
    "Vendée": " de la ",
    "Vienne": " de la ",
    "Vosges": " des ",
    "Wallis-et-Futuna": " de ",
    "Yonne": " de l'",
    "Yvelines": " des ",
}

export default departments_preposition;